[package]
name = "web_server"
version = "0.1.0"
authors = ["Luke Matthews <lmtthws@gmail.com>"]
edition = "2018"

[dependencies]
uri = { path = "../uri" }
thread_pool = { path = "../thread_pool" }

